plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {

    // Source: https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java
    implementation("org.seleniumhq.selenium:selenium-java:4.40.0")

    // Source: https://mvnrepository.com/artifact/org.testng/testng
    testImplementation("org.testng:testng:7.11.0")


    // Source: https://mvnrepository.com/artifact/com.github.javafaker/javafaker
    implementation("com.github.javafaker:javafaker:1.0.2")

    // Source: https://mvnrepository.com/artifact/com.googlecode.json-simple/json-simple
    implementation("com.googlecode.json-simple:json-simple:1.1.1")



}


test{

    useTestNG(){

        if (project.hasProperty("email") && project.hasProperty("password"))

        {
            systemProperties.put("email",project.property("email"))
            systemProperties.put("password",project.property("password"))

            print(project.property("email"))
            print(project.property("password"))

        }

        suites "src/test/resources/suite.xml"
    }

    testLogging {
        events "passed", "failed", "skipped", "standard_out"
        showStandardStreams = true
    }


}


