plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {

    // Source: https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java
    implementation("org.seleniumhq.selenium:selenium-java:4.40.0")

    // Source: https://mvnrepository.com/artifact/org.testng/testng
    testImplementation("org.testng:testng:7.11.0")


    // Source: https://mvnrepository.com/artifact/com.github.javafaker/javafaker
    implementation("com.github.javafaker:javafaker:1.0.2")

    // Source: https://mvnrepository.com/artifact/com.googlecode.json-simple/json-simple
    implementation("com.googlecode.json-simple:json-simple:1.1.1")

    implementation 'io.qameta.allure:allure-testng:2.34.0'

    testImplementation("io.rest-assured:rest-assured:6.0.0")

}


//test{
//
//    useTestNG(){
//
//        if (project.hasProperty("email") && project.hasProperty("password"))
//
//        {
//            systemProperties.put("email",project.property("email"))
//            systemProperties.put("password",project.property("password"))
//
//            print(project.property("email"))
//            print(project.property("password"))
//
//        }
//
////       if (project.hasProperty("suite")){
////
////           systemProperties.put(suite,project.property("suite"))
////       }
//
//        suites "./src/test/resources/" + project.property("suite")
//    }
//
//    testLogging {
//        events "passed", "failed", "skipped", "standard_out"
//        showStandardStreams = true
//    }


    test {

        useTestNG() {

            if (project.hasProperty("email") && project.hasProperty("password")) {

                systemProperty "email", project.property("email")
                systemProperty "password", project.property("password")

                println project.property("email")
                println project.property("password")
            }

            if (project.hasProperty("suite")) {
                suites "./src/test/resources/" + project.property("suite")
            }

        }

        testLogging {
            events "passed", "failed", "skipped", "standard_out"
            showStandardStreams = true
        }
    }




